apiVersion: v1
kind: Secret
metadata:
  name: my-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/bijuthottathil/AWS-EKS.git
  username:bijuthottathil       # Optional for public repos
  password:
  type: git
