apiVersion: v1
kind: Secret
metadata:
  name: my-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/bijuthottathil/AWS-EKS.git
  username: bijuthottathil
  password: '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'
  type: git
